"use client";
import Image from "next/image";
import Link from "next/link";
import { motion, useInView } from "framer-motion";
import { useRef, type ReactNode } from "react";
import { SectionReveal } from "@/animations/motion";
import { imageHover, staggerChildren } from "@/animations/variants";
import { Icon, type IconName } from "@/components/shared/icon";
import { PortraitPlaceholder } from "@/components/shared/placeholder";
import { Button } from "@/components/ui/button";
import { PortfolioCard, ServiceCard } from "@/components/ui/card";
import { imageSet, portfolioItems, services } from "@/sections/home/data";
export function PortfolioSection() { return <SectionReveal className="container-luxury py-20 lg:py-30"><SectionHeading eyebrow="Selected work" title="Stories that stay with you." action={<Link href="/portfolio"><Button variant="secondary">View Collection</Button></Link>} /><motion.div variants={staggerChildren} initial="hidden" whileInView="visible" viewport={{ once: true }} className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{portfolioItems.map((item) => <motion.div key={item.id} variants={{ hidden: { opacity: 0, y: 16 }, visible: { opacity: 1, y: 0 } }}><PortfolioCard title={item.title} category={item.category}><motion.div variants={imageHover} initial="rest" whileHover="hover" className="relative aspect-[4/5]"><Image src={item.thumbnailUrl} alt={item.alt} fill sizes="(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw" className="object-cover" /></motion.div></PortfolioCard></motion.div>)}</motion.div></SectionReveal>; }
export function AboutPreview() { return <SectionReveal className="bg-surface py-20 lg:py-30"><div className="container-luxury grid items-center gap-10 lg:grid-cols-2 lg:gap-18"><div className="relative mx-auto aspect-[4/5] w-full max-w-md overflow-hidden border border-white/10"><PortraitPlaceholder /></div><div><p className="eyebrow">The artist behind the lens</p><h2 className="text-display-lg mt-4">Hi, I&apos;m <em className="font-normal text-gold">Akshay Markad</em></h2><div className="mt-6 space-y-5 text-body text-white/80"><p>Hi, I&apos;m Akshay Markad, a Pune-based photographer passionate about capturing genuine emotions and timeless memories.</p><p>My photography style combines cinematic storytelling with natural moments to create images that people will cherish for generations.</p><p>Every wedding, couple shoot, event and maternity session is approached with creativity, emotion and attention to detail.</p></div><Link href="/contact" className="mt-8 inline-block"><Button variant="secondary">Book a Session</Button></Link></div></div></SectionReveal>; }
export function ServicesSection() { return <SectionReveal className="container-luxury py-20 lg:py-30"><SectionHeading eyebrow="What I do" title="Made for moments that matter." /><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{services.map((service) => <motion.div key={service.title} whileHover={{ y: -5 }} transition={{ duration: 0.25 }}><ServiceCard title={service.title} description={service.description} className="h-full"><Icon name={service.icon as IconName} className="h-8 w-8 text-gold" /></ServiceCard></motion.div>)}</div></SectionReveal>; }
function Counter({ value, label }: { value: number; label: string }) { const ref = useRef<HTMLDivElement>(null); const inView = useInView(ref, { once: true }); return <div ref={ref}><motion.p className="font-display text-4xl text-gold" initial={{ opacity: 0 }} animate={inView ? { opacity: 1 } : {}}>{inView ? `${value}+` : "—"}</motion.p><p className="mt-2 text-xs uppercase tracking-[0.16em] text-text-secondary">{label}</p></div>; }
export function WhyChooseMe() { const features = [["Creative Storytelling", "Images with feeling, rhythm and a point of view."], ["Premium Editing", "A refined editorial finish that ages beautifully."], ["Travel Across India", "Available wherever your celebration takes place."], ["Fast Delivery", "A thoughtful, reliable process from inquiry to gallery."]]; return <SectionReveal className="bg-surface py-20 lg:py-30"><div className="container-luxury grid gap-12 lg:grid-cols-2"><div><p className="eyebrow">The experience</p><h2 className="text-display-lg mt-4">Crafted with care.<br /><em className="font-normal text-gold">Delivered with purpose.</em></h2><div className="mt-10 grid grid-cols-2 gap-7 border-y border-white/10 py-8 sm:grid-cols-4">{[[250, "Happy Clients"], [480, "Projects"], [24, "Cities Covered"], [8, "Years Experience"]].map(([value, label]) => <Counter key={label as string} value={value as number} label={label as string} />)}</div></div><div className="grid gap-4 sm:grid-cols-2">{features.map(([title, text], index) => <motion.div key={title} whileHover={{ borderColor: "rgba(200,164,93,0.6)" }} className="border border-white/10 p-6"><span className="text-gold">0{index + 1}</span><h3 className="mt-8 font-display text-2xl">{title}</h3><p className="mt-3 text-sm leading-6 text-text-secondary">{text}</p></motion.div>)}</div></div></SectionReveal>; }
export function InstagramSection() { return <SectionReveal className="container-luxury py-20 lg:py-30"><SectionHeading eyebrow="@akshaymarkadphotography" title="Follow My Journey" action={<a href="https://instagram.com" target="_blank" rel="noreferrer"><Button variant="secondary">Visit Instagram</Button></a>} /><div className="mt-10 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{imageSet.map((src, index) => <motion.a key={src} href="https://instagram.com" target="_blank" rel="noreferrer" variants={imageHover} initial="rest" whileHover="hover" className="relative aspect-square overflow-hidden"><Image src={src} alt={`Instagram photography preview ${index + 1}`} fill sizes="(min-width: 1024px) 16vw, 50vw" className="object-cover" /></motion.a>)}</div></SectionReveal>; }
export function BookingCta() { return <SectionReveal className="border-y border-white/10 bg-black py-20 text-center lg:py-30"><div className="container-luxury"><p className="eyebrow">Let&apos;s create memories together.</p><h2 className="text-display-lg mx-auto mt-4 max-w-3xl">Begin your next chapter with a timeless luxury session.</h2><div className="mt-9 flex flex-wrap justify-center gap-3"><Link href="/contact"><Button>Book Now</Button></Link><a href="https://wa.me/919604818752" target="_blank" rel="noreferrer"><Button variant="secondary">WhatsApp</Button></a></div></div></SectionReveal>; }
function SectionHeading({ eyebrow, title, action }: { eyebrow: string; title: string; action?: ReactNode }) { return <div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="eyebrow">{eyebrow}</p><h2 className="text-display-lg mt-4">{title}</h2></div>{action}</div>; }
