"use client";
import Link from "next/link";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { useEffect, useState } from "react";
import { navigationItems } from "@/constants/navigation";
import { cn } from "@/utils/cn";
export function Navbar() {
  const [open, setOpen] = useState(false); const [scrolled, setScrolled] = useState(false); const reduce = useReducedMotion();
  useEffect(() => { const update = () => setScrolled(window.scrollY > 16); update(); window.addEventListener("scroll", update, { passive: true }); return () => window.removeEventListener("scroll", update); }, []);
  useEffect(() => { document.body.style.overflow = open ? "hidden" : ""; return () => { document.body.style.overflow = ""; }; }, [open]);
  return <header className={cn("fixed inset-x-0 top-0 z-40 transition-colors duration-300", scrolled || open ? "bg-canvas/95 backdrop-blur-md" : "bg-transparent")}><nav className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:grid lg:grid-cols-3 lg:px-8" aria-label="Primary"><div className="hidden lg:flex lg:gap-7">{navigationItems.slice(0, 2).map((item) => <NavLink key={item.href} {...item} />)}</div><Link href="/" className="font-display text-xl tracking-[0.12em] text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gold" aria-label="Akshay Markad Photography home">AKSHAY MARKAD</Link><div className="hidden justify-end gap-7 lg:flex">{navigationItems.slice(2).map((item) => <NavLink key={item.href} {...item} />)}</div><button type="button" className="relative z-50 inline-flex h-11 w-11 items-center justify-center text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gold lg:hidden" onClick={() => setOpen((value) => !value)} aria-expanded={open} aria-controls="mobile-navigation" aria-label={open ? "Close navigation" : "Open navigation"}><span className={cn("absolute h-px w-6 bg-current transition-transform", open && "rotate-45")} /><span className={cn("absolute h-px w-6 bg-current transition-transform", open && "-rotate-45")} /></button></nav><AnimatePresence>{open && <motion.div id="mobile-navigation" initial={reduce ? false : { opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 grid place-items-center bg-canvas"><div className="flex flex-col items-center gap-7">{navigationItems.map((item, index) => <motion.div key={item.href} initial={reduce ? false : { opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0, transition: { delay: index * 0.06 } }}><Link href={item.href} onClick={() => setOpen(false)} className="font-display text-4xl text-white transition-colors hover:text-gold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gold">{item.label}</Link></motion.div>)}</div></motion.div>}</AnimatePresence></header>;
}
function NavLink({ label, href }: { label: string; href: string }) { return <Link href={href} className="group relative py-2 text-xs font-medium uppercase tracking-[0.18em] text-white/80 transition-colors hover:text-gold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gold"><span>{label}</span><span className="absolute inset-x-0 -bottom-0 h-px origin-left scale-x-0 bg-gold transition-transform duration-300 group-hover:scale-x-100" /></Link>; }
